### ISSUE TITLE
Fix wrong wording

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-k8s-operator#101]
### Enhancement Proposal

After https://github.com/zalando/patroni/issues/2495 is solved (including k8s pod labels), change every occurrence of `master` to `primary` in the code.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by marceloneppel** [comment]
Yes, we do. https://warthogs.atlassian.net/browse/DPE-1177.

**Comment by taurus-forever** [comment]
Fixed in https://github.com/canonical/postgresql-k8s-operator/pull/532 , resolved.
