### ISSUE TITLE
Cross-model K8s relations

### ISSUE THREAD

**Issue by AmberCharitos** [canonical/postgresql-k8s-operator#206]
The Commercial Systems team is working on creating a data platform for use internally at Canonical. As part of this we require the ability to relate a k8s charm we are creating cross-model to a K8s PostgreSQL charm running on a different cluster. We have spoken to a number of people from the data platform team and been told this functionality is currently not available. 

As the charms will be on different clusters without this functionality we are not able to make a relation, and are currently using actions to provide configuration values which we would prefer to avoid.

**Comment by marceloneppel** [comment]
Hi @AmberCharitos! This is a feature we should work in this cycle. We are currently starting by another feature, but will move to this one after that.

**Comment by AmberCharitos** [comment]
Good to know - thanks @marceloneppel !

**Comment by taurus-forever** [comment]
@AmberCharitos can you please check and give us feedback on the current Async replication feature (we are preparing for the stable release now): https://charmhub.io/postgresql-k8s/docs/h-async-set-up

It should close this issue. Tnx!

**Comment by taurus-forever** [comment]
Dear  @AmberCharitos ,

Can you please check my last reply? We believe this is no longer topical. Thank you!

**Comment by taurus-forever** [comment]
Resolving as no reply and should no longer be topical and cross-model/controller works for Async replication.
Feel free to reopen this issue (or better create a new bugreport if you experiencing cross-model/controller relation issues).
Tnx!
