### ISSUE TITLE
clean deployment not starting up the postgresql service

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/postgresql-k8s-operator#227]
## Steps to reproduce
Unable to provide. This happened on a clean deployment of the charm

## Expected behavior
The charm starts up

## Actual behavior
The charm gets stuck on waiting status "awaiting for cluster to start". The postgresql pebble service doesn't start up and there are no logs for it.
When inspecting the k8s resources, the postgresql pod is missing several labels, although the logs indicate the resource has been successfully patched:
``` 
Labels:           app.juju.is/created-by=postgresql
                  app.kubernetes.io/name=postgresql
                  controller-revision-hash=postgresql-5677dcb85c
                  statefulset.kubernetes.io/pod-name=postgresql-0
```
Missing labels are:
```
                  application=patroni
                  cluster-name=patroni-postgresql
                  role=master
```

## Versions

Operating system: Ubuntu 20.04.6 LTS

Juju CLI: 2.9.44-ubuntu-amd64

Juju agent: 2.9.44

Charm revision: 122

k8s: v1.21.14 

## Log output

Juju debug log:

**Comment by taurus-forever** [comment]
@arturo-seijas some extra questions:
Q1: Does it happen randomly or constantly?
`Operating system: Ubuntu 20.04.6 LTS`, Q2: are you deploying `jammy` or `focal`?
Q3: Is `k8s: v1.21.14` microk8s?
Thank you!

**Comment by dragomirp** [comment]
> @arturo-seijas some extra questions: Q1: Does it happen randomly or constantly? `Operating system: Ubuntu 20.04.6 LTS`, Q2: are you deploying `jammy` or `focal`? Q3: Is `k8s: v1.21.14` microk8s? Thank you!

Hi, this is a followup ticket. It happened on their stg-cluster. It's a random occurrence and cleaning up k8s resources salvaged the deployment.

**Comment by marceloneppel** [comment]
After chatting with Juju team on https://chat.charmhub.io/charmhub/pl/ojdbe5dw3jge9bdsd1tkeypopw we will work on a way to remove the needed k8s resources when the charm is installed (in a new deployment).
