### ISSUE TITLE
[doc] Add how-to for integrating with postgresql

### ISSUE THREAD

**Issue by sed-i** [canonical/postgresql-k8s-operator#237]
Your docs on discourse are awesome :bowing_man: 

I would like to integrate with a new charm I'm writing and I didn't see a doc for _that_.

In particular:
- Does the requirer need to set anything in reldata?
- Is there a charm lib for that, or does my charm need to compile the postgresql reldata on its own?
- How do I obtain the database url?

In the meanwhile I can try and look at how [discourse](https://github.com/canonical/discourse-k8s-operator) did it.

**Comment by dragomirp** [comment]
Hi, @sed-i, most existing charms currently use [ops-lib-pgsql](https://github.com/canonical/ops-lib-pgsql) interface, but we would prefer for new charms to use [data-platform-libs](https://github.com/canonical/data-platform-libs) instead. You can take a look at [postgresql-test-app](https://github.com/canonical/postgresql-test-app) and [juju-sdk-tutorial-k8s](https://github.com/canonical/juju-sdk-tutorial-k8s) for more practical examples.

**Comment by taurus-forever** [comment]
@sed-i thank you for the feedback!

We have created the following document https://charmhub.io/postgresql-k8s/docs/h-development-mycharm to answer your questions and will be happy if you help us make it better. Should we resolve this issue? Tnx!

**Comment by taurus-forever** [comment]
Resolved as no updates on the last post. Feel free to reopen if still topical.
