### ISSUE TITLE
Extensions not enabled on clean deployment

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/postgresql-k8s-operator#239]
## Steps to reproduce

1.  Deploy postgresql-k8s with enabled extensions

```
postgresql_config = {
    "plugin_pg_trgm_enable": True,
    "plugin_unaccent_enable": True,
}
ops_test.model.deploy(
    "postgresql-k8s", channel="14/edge", config=postgresql_config, trust=True
)
## Expected behavior
The database ha the specified extensions enabled.

## Actual behavior
Although the charm configuration is fine when running a `juju status`, the extensions have not been enabled.


## Versions

<!-- Run `lsb_release -sd` -->
Operating system: Ubuntu 20.04.6 LTS

<!-- Run `juju version` -->
Juju CLI: 2.9.44-ubuntu-amd64

<!-- Model version from `juju status` -->
Juju agent: 2.9.44

<!-- App revision from `juju status` or (advanced) commit hash -->
Charm revision: 132

<!-- Run `microk8s version` -->
microk8s: None, this is a full k8s distro

## Log output
<!-- Please enable debug logging by running `juju model-config logging-config="<root>=INFO;unit=DEBUG"` (if possible) -->
<!-- Then, run `juju debug-log --replay > log.txt` and upload "log.txt" file here -->
Juju debug log: Not relevant

<!-- (Optional) Copy the logs that are relevant to the bug & paste inside triple backticks below -->


## Additional context
<!-- (Optional) Add any additional information here -->

**Comment by dragomirp** [comment]
Look like extensions behaviour is confusing and doesn't give an indication of when the changes are applied. We'll add a unit status update, to improve visibility.

**Comment by dragomirp** [comment]
Should be solved in latest edge (rev. 159)

**Comment by dragomirp** [comment]
Looks like we still need to do more checks here.

**Comment by dragomirp** [comment]
Investigating further, it looks to me that postgresql work as intended and the new failures happen due to some kind of race in the redis relation. Testing on a [forked repo](https://github.com/dragomirp/indico-operator/pull/1/commits/e775c94cf171e082119ab43757e9246db234ba32), tests (bar the SAML test) succeed consistently. Leaving this issue open until @arturo-seijas has a chance to confirm.

**Comment by arturo-seijas** [comment]
I've been able to confirm it @dragomirp , and it seems like it might be related to the Indico charm itself.

I'm closing the ticket.

Thank you very much :)
