### ISSUE TITLE
Scaling postgresql-k8s to 0 and then back to 3 results in hook failed: leader-elected

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/postgresql-k8s-operator#247]
## Steps to reproduce

1. Deploy postgresql-k8s along with an application to use it.
2. Configure backups and create a backup.
3. Scale Postgresql-k8s to zero, allow to complete
4. Scale postgresql-k8s to 3, see leader-elected error

## Expected behavior
Scaling postgresql-k8s back to 3 successfully creates a cluster.

## Actual behavior
Hook failed error

## Versions

Operating system: 22.04
Juju CLI: 3.1.5-genericlinux-amd64
Juju agent: 3.1.5
Charm revision: 14/edge/pr240
microk8s: v1.28.0 revision 5802

## Log output
https://pastebin.canonical.com/p/GB92bBrJGS/

## Additional context
Juju status: https://pastebin.canonical.com/p/KNVsf3QX8Z/

**Comment by marceloneppel** [comment]
Hi @cjohnston1158! We're currently working on this issue in this pulse. We found the fix for that situation and now we're working on applying it on both the K8S and teh VM charms.

**Comment by marceloneppel** [comment]
Hi @cjohnston1158! Revision 176 from 14/edge channel contains the fix for this.
