### ISSUE TITLE
Misleading header in security docs

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/postgresql-k8s-operator#267]
The [Enable Security in your PostgreSQL deployment](https://charmhub.io/postgresql-k8s/docs/t-enable-security?channel=14/edge) page has a misleading header. **Add external TLS certificate** sounds like an action is going to be taken to add a cert that is not generated by the tls-certificates-operator charm. Instead, the contents of this section is just checking to see if postgresql is using a certificate.

**Comment by taurus-forever** [comment]
Fixed for PostgreSQL and MySQL manuals VM+K8s.
