### ISSUE TITLE
Update security docs

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/postgresql-k8s-operator#272]
With support for self signed certs being removed from tls-certificates-operator, the docs need to be updated for self-signed to use the self-signed-certificates charm and tls-certificates-operator otherwise.

**Comment by taurus-forever** [comment]
@cjohnston1158 , tnx for the report!
The postgresql(-k8s) charm supports both Juju 2.9 and Juju 3.1 but self-signed-certificates is designed for Juju 3.1 only.
The plan is to use `tls-certificates-operator` for Juju 2.9 from channel `legacy/stable` and `self-signed-certificates` for Juju 3.1+

**Comment by taurus-forever** [comment]
Dear @cjohnston1158 all SQL documentation migrated from tls-certificates-operator to self-signed-certificates. Resolved.

CC: Tnx to @a-velasco !
