### ISSUE TITLE
Port Indico test to new relation

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-k8s-operator#305]
Indico charm recently changed to use the new relation (through `postgresql_client` interface).

**Comment by taurus-forever** [comment]
@dragomirp I think it is no longer topica.
1) Indico [postgresql_client](https://charmhub.io/integrations/postgresql_client) is in stable.
2) [we are testing against stable](https://github.com/canonical/postgresql-k8s-operator/blob/main/tests/integration/new_relations/test_new_relations.py#L693).

Resolved?

**Comment by dragomirp** [comment]
> @dragomirp I think it is no longer topica.
> 
>     1. Indico [postgresql_client](https://charmhub.io/indico/integrations#database) is in stable.
> 
>     2. [we are testing against stable](https://github.com/canonical/postgresql-k8s-operator/blob/main/tests/integration/new_relations/test_new_relations.py#L693).
> 
> 
> Resolved?

Looks like it.
