### ISSUE TITLE
Secure Patroni REST API from unauthorized access

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-k8s-operator#33]
Secure the Patroni REST API to prevent misuse, like the commented example [here](https://github.com/canonical/postgresql-k8s-operator/pull/26#discussion_r955963163).

**Comment by taurus-forever** [comment]
Reported internally as DPE-1045.

**Comment by taurus-forever** [comment]
This has been improved and released in https://charmhub.io/postgresql-k8s/docs/r-revision-381-382
Resolved as no longer topical.

P.S. users can still read from Patroni without the authentication but reconfiguration is protected (default Patroni logic).
