### ISSUE TITLE
postgresql-k8s integration with tls-certificates-operator doesn't work

### ISSUE THREAD

**Issue by nsakkos** [canonical/postgresql-k8s-operator#398]
## Steps to reproduce

Following the [tutorial](https://canonical.com/data/docs/postgresql/k8s/t-enable-security) to deploy postgresql-k8s and enable security: 

1. juju deploy postgresql-k8s --channel 14/stable --trust
2. juju deploy tls-certificates-operator --config generate-self-signed-certificates="true" --config ca-common-name="Tutorial CA"
3. juju integrate postgresql-k8s tls-certificates-operator

## Expected behavior
```
> openssl s_client -starttls postgres -connect POSTGRESQL_IP:5432 | grep Issuer
...
depth=1 C = US, CN = Tutorial CA
verify error:num=19:self-signed certificate in certificate chain
```
...

## Actual behavior

![image](https://github.com/canonical/postgresql-k8s-operator/assets/100378456/f02e4156-1f72-41ee-8ff1-35bbec46b36d)

## Versions

Operating system: Ubuntu 22.04.4 LTS (charmed-dev multipass blueprint)

Juju CLI: 3.1.7

Juju agent: 3.1.7

Charm revision: 
postgresql-k8s 14/stable rev 177
tls-certificates-operator  stable rev 22

microk8s: MicroK8s v1.27.11 revision 6530

## Log output

Juju debug log: 
[log.txt](https://github.com/canonical/postgresql-k8s-operator/files/14352215/log.txt)

**Comment by dragomirp** [comment]
Hi, @nsakkos, there are issues with secrets on `14/stable` (rev. 177) and Juju 3.1.7. Please, try `14/candidate` (rev. 193), it fixes the issue and should be promoted to `14/stable` soon.

**Comment by nsakkos** [comment]
Hi @dragomirp, thank you for the update. I confirm that it works with 14/candidate .

**Comment by dragomirp** [comment]
Closing as the issue will be fixed when candidate is promoted.
