### ISSUE TITLE
Charmed deployment stuck on postgres "awaiting for primary endpoint to be ready"

### ISSUE THREAD

**Issue by kbaccar-core** [canonical/postgresql-k8s-operator#552]
Hello,
Im following the main documentation to run charmed magma. Everything went approximately as expected, except for the deployment of the charm with this command: juju deploy magma-orc8r --overlay overlay.yaml --trust --channel=latest
Apparently the postgres application is stuck on " awaiting for primary endpoint to be ready".

## Environment
Charm version: 1.8
Postgres Version: 14/edge
Affected Component: Postgres
Deployment Environment: AWS (orc8r)

## Sceeenshot

Juju Status:

<img width="635" alt="magmacore1" src="https://github.com/canonical/postgresql-k8s-operator/assets/174700204/8f5f28ac-0ca1-4222-b58a-247f77c3f83d">

Juju Postgrs log:

<img width="677" alt="magmacore2" src="https://github.com/canonical/postgresql-k8s-operator/assets/174700204/c10516c0-edc0-497f-84c5-c73ce9a0dea2">

**Comment by dragomirp** [comment]
Hi, @kbaccar-core, IIRC there was an incompatibility between the charm and Juju 3.5.0. Can you try redeploying it on Juju 3.5.1 or Juju 3.4?

**Comment by taurus-forever** [comment]
I am resolving this issue, as the modern charm revisions clearly insist/assumes in [Juju 3.5.1+](https://github.com/canonical/postgresql-k8s-operator/blob/main/metadata.yaml#L84-L95).

Also we have updated the list of supported Juju versions with the patch set level precision: https://charmhub.io/postgresql-k8s/docs/r-system-requirements (we will continue the work here to represent it better).

Dear @kbaccar-core Feel free to reopen this issue IF it is still reproducible on your side for modern/fixed Juju versions. Tnx!
