### ISSUE TITLE
Scaling breaks "The S3 repository has backups from another cluster" blocked status

### ISSUE THREAD

**Issue by Zvirovyi** [canonical/postgresql-k8s-operator#591]
## Steps to reproduce

1. juju deploy s3-integrator
2. juju deploy postgresql-k8s --config profile=testing --channel edge --trust
3. _configure s3-integrator to use bucket with backups from another cluster_
4. juju integrate s3-integrator postgresql-k8s
5. as it should be, cluster became in `The S3 repository has backups from another cluster` blocked status
    ![Screenshot](https://github.com/user-attachments/assets/95041e26-c781-4e7e-a978-63a952128f8e)
6. juju scale-application postgresql-k8s 2
7. after scale, cluster loose it's blocked status and became active idle
    ![Screenshot](https://github.com/user-attachments/assets/5996eac0-b69d-4b6d-97d8-f88342b8fad7)

## Expected behavior
Cluster should keep it's blocked status `The S3 repository has backups from another cluster` even after scaling.

## Actual behavior
See step 7.

## Versions

Operating system: Ubuntu 24.04 LTS

Juju CLI: 3.5.2-genericlinux-amd64

Juju agent: 3.5.2

Charm revision: 327

microk8s: MicroK8s v1.30.0 revision 6783

## Log output

Juju debug log: [debug-log](https://github.com/user-attachments/files/16390452/new_issue.log)

## Additional context

From the work on [Point In Time Recovery](https://github.com/canonical/postgresql-k8s-operator/pull/554), i can suggest to refactor logic of this blocked message. Now, `The S3 repository has backups from another cluster` message sets in `PostgreSQLBackups._on_s3_credential_changed` by `can_use_s3_repository` func and it's supposed not to be overridden by any of events. But it's better to keep this status in `app_peer_data` and set this message in `PostgresqlOperatorCharm._set_active_status` function as it works with blocked status `Move restored cluster to another S3 bucket` introduced by the PITR work in the PR referenced above.

**Comment by taurus-forever** [comment]
This is a valid bugreport and lets keep it opened, however we should focus on removal this blocking message completely (managing timelines during recovery) and not fixing this issue. @marceloneppel ACK?

**Comment by Zvirovyi** [comment]
@taurus-forever 

Timelines management will:
* allow us not to use `Move restored cluster to another S3 bucket` logic
* allow user to see all the lifespan of cluster (not just separated to different S3 buckets after each restore) and effectively navigate through different timelines of it
* imply WAL archiving refactor, that will fix issues like [this](https://github.com/canonical/postgresql-operator/issues/463) (not sure if there is the same bug)

But, error `The S3 repository has backups from another cluster` is different as it indicates that pgBackRest stanza is configured for another cluster. From the quick research, pgBackRest does not support such scenario. Also, it may cause some errors like same timelines from different clusters will conflict with each other. Anyway, this will require deeper research and it's not related to the PITR.

**Comment by marceloneppel** [comment]
@taurus-forever: @Zvirovyi is right. The message that is gone after scaling the cluster is related to pointing the cluster to a backup repository from another cluster, not from a different timeline of the same cluster.
