### ISSUE TITLE
Wrong description for action `get-password`

### ISSUE THREAD

**Issue by goulinkh** [canonical/postgresql-k8s-operator#603]
## Expected behavior

A general description and comments regarding the action `get-password`.

## Actual behavior

The description of `set-password` instead `get-password`.

**Comment by marceloneppel** [comment]
Good catch! Thanks for reporting that, @goulinkh! https://github.com/canonical/postgresql-k8s-operator/pull/605 is fixing it.

**Comment by marceloneppel** [comment]
Revisions 344 and 345 contain the fix.
