### ISSUE TITLE
Jammy series not supported

### ISSUE THREAD

**Issue by natalian98** [canonical/postgresql-k8s-operator#62]
If `juju model-config` is set to the latest LTS `default-series=jammy`, postgresql-k8s edge can't be deployed.

Since yesterday, when I'm trying to deploy it, I get a message that jammy is not supported:
```
$ juju deploy postgresql-k8s --channel edge --trust
ERROR series "jammy" not supported by charm, supported series are: focal. Use --force to deploy the charm anyway. Used the default-series.
```
When I use the force flag, the message says that rev29 (latest/edge) can't be found:
```
$ juju deploy postgresql-k8s --channel edge --trust --force
Located charm "postgresql-k8s" in charm-hub, revision 29
ERROR listing resources for charm "ch:amd64/jammy/postgresql-k8s-29": No revision was found in the Store.
```
The workaround is to set `juju model-config default-series=focal` even if the charm is deployed on jammy.

Is it an expected behaviour?

**Comment by taurus-forever** [comment]
Dear @natalian98,

I think it is expected, the charm support focal only at the moment
> https://github.com/canonical/postgresql-k8s-operator/blob/main/charmcraft.yaml#L2

We have 'jammy' support in our TODO list. I believe you still can deploy the specific 'series' charm even without 'default-series' set. Can you please try:
> juju deploy postgresql-k8s --channel edge --trust **--series 'focal'**

I am resolving the issue, feel free reopen it if necessary.
