### ISSUE TITLE
Table permissions issue on relation recreated

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/postgresql-k8s-operator#64]
There is a permission issue on tables when relation is recreated

Test scenario is simple:
add any charm that uses psql and psql itself, relate:
```
juju add-model model2
juju deploy postgresql-k8s --channel=edge
juju deploy ./demo-api-charm_ubuntu-22.04-amd64.charm --resource      demo-server-image=ghcr.io/beliaev-maksim/api_demo_server:0.0.9
juju status --watch 2s
juju integrate demo-api-charm postgresql-k8s
juju status --watch 2s
```

Now remove relation and recreate relation:

```
juju remove-relation  demo-api-charm postgresql-k8s
juju integrate demo-api-charm postgresql-k8s
```

Now application charm cannot access DB table due to permissions issue. We receive new credentials because user name is bound to relation ID, but it looks like this user does not have access to tables inside DB.
I would assume we need a recursive permission.

Here is application error log about table permissions:
```
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/./api_demo_server/app.py", line 82, in get_all_names
    return {"names": dict(PSQL_DB.all_names(db_name="names_db", table_name="names"))}
  File "/./api_demo_server/database.py", line 110, in all_names
    cursor.execute(sql.SQL("SELECT * FROM {}").format(sql.Identifier(table_name)))
psycopg2.errors.InsufficientPrivilege: permission denied for table names
```

**Comment by taurus-forever** [comment]
The reported issue should be addressed with the commit above. Resolving the ticket.
Please check it from your side and reopen if necessary! Thank you for reporting it!
